# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExHealthKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExHealthKit

pod 'SnapKit', '~> 5.6.0'
pod 'RxSwift', '6.5.0'
pod 'RxCocoa'

end
